### ISSUE TITLE
How to disable multirust check on startup?

### ISSUE THREAD

**Issue by chessnokov** [vertexclique/tokamak#10]
How to disable multirust?

**Comment by TofPlay** [comment]
I have also some erreur with multirust. Is not installed on my machine.
![image](https://cloud.githubusercontent.com/assets/1082222/14292687/72034166-fb69-11e5-92a7-b8bb3fccbcef.png)

**Comment by vertexclique** [comment]
In settings:
![settings-tokamak](https://cloud.githubusercontent.com/assets/578559/14292717/faacc6ec-fb71-11e5-9b91-a965f822dc71.png)

**Comment by chessnokov** [comment]
![2016-04-05 21-10-54](https://cloud.githubusercontent.com/assets/1489752/14292965/0d43f86a-fb73-11e5-9dfa-edc47aae46e5.png)

**Comment by TofPlay** [comment]
Same as @chessnokov

**Comment by vertexclique** [comment]
As error information descriptive your PATH doesn't contain multirust.
Can you add it and try again?

**Comment by chessnokov** [comment]
@vertexclique I do not use multirust, prefer to install manually rust from source.
Is it possible to use tokamak without multirust?

**Comment by vertexclique** [comment]
Ok this is a feature request so I will mark this as enhancement. Answer of the question is not yet.

**Comment by nmabhinandan** [comment]
Toolchain handling should not be the responsibility of any IDE. Would be great if that's refactored out to a separate(optional) plugin/feature.
