### ISSUE TITLE
Claims cannot find rustc etc on Windows

### ISSUE THREAD

**Issue by dten** [vertexclique/tokamak#2]
https://github.com/vertexclique/tokamak/blob/c38cb507ae758c7ef75c450a0da5440d6bd45951/lib/tokamak.coffee#L191

This is using `where` to see if stuff is on the path. `where` isn't a thing in Windows (although `which` is).

Also I get the error despite manually setting the paths

![image](https://cloud.githubusercontent.com/assets/1019038/14264140/6aea5d5a-fab6-11e5-990a-dd653c20850c.png)

**Comment by Diggsey** [comment]
@dten You've got that the wrong way around: `where` *is* a thing on windows, but `which` isn't (unless you have msys on your PATH)

**Comment by dten** [comment]
Yep. I always get that the wrong way around :D anyway it's using a unix only thing which doesn't exist on windows
