### ISSUE TITLE
Toolbar icons too big.

### ISSUE THREAD

**Issue by kindlychung** [vertexclique/tokamak#24]
They take way too much space. 

Better yet, why not give an option for disabling the toolbar? You don't need it if you remember the keyboard shortcuts.

**Comment by vertexclique** [comment]
You can use this settings pane:

![screen shot 2016-04-15 at 20 52 17](https://cloud.githubusercontent.com/assets/578559/14575790/683e413c-0364-11e6-9e19-4b8d98a25769.png)

But I will add the toggle to tokamak anyways
