### ISSUE TITLE
The Terminal doesn't work under Fedora Linux

### ISSUE THREAD

**Issue by flo-l** [vertexclique/tokamak#40]
I'm having issues with the terminal. When I open it manually or click on the cargo test/run buttons it just stays black/empty and does nothing. I also can't enter any commands.

Screenshot:
![tokamak_screenshot](https://cloud.githubusercontent.com/assets/5130545/15096611/11715a0c-1501-11e6-91ca-8cbae2f95bcd.png)

**Comment by vertexclique** [comment]
That should go to https://github.com/vertexclique/tokamak-terminal and probably there is already one in there.

https://github.com/vertexclique/tokamak-terminal/issues/4
