### ISSUE TITLE
Multirust No Longer Maintained

### ISSUE THREAD

**Issue by qingxiang-jia** [vertexclique/tokamak#42]
I was trying to set up my tokamak, but found that multirust is no longer maintained and the author suggested rustup.rs. Although we can still use multirust, is there any plan for a switch?

Thanks.

**Comment by xavier83** [comment]
Already in progress! https://github.com/vertexclique/tokamak/pull/30

**Comment by qingxiang-jia** [comment]
I see. Thanks!
