### ISSUE TITLE
path problem

### ISSUE THREAD

**Issue by dizergin** [vertexclique/tokamak#48]
Famous  cargo binary path problem.. "Uncaught TypeError: item.save is not a function" 
Yes , I am aware of the discussion upon the topic.. but NONE of suggested workabouts is good for me.
The problem: The tokamak  can not do anything with the cargo.exe commands.
The details:
The Racer atom's component does not work too even stand alone(without tokamak)- I suspect for the same reason . The linter atom's component works  well (It implies on correctly set the rust environment). The Racer set up correctly  and works well(out of the Atom). The autodetection results visually correct paths in the proper fields. Yet nasty autodetection toolchain  problem presents at the atom's start - may be it prevents the tokamak from its regular workflow?  Of course the cargo tool works just fine from a command line.
The Rust environment was set up with the rustup tool (default options for msvs(abi) of the stable channel ). OS Windows 10. atom v1.8.0. tokamak v 0.2.7

**Comment by dizergin** [comment]
upd: the bug was in the autodetect procedure - endline symbol was add on every path field through its execution

**Comment by vadixidav** [comment]
Shouldn't this still be open then? This is still an issue for people.

**Comment by dizergin** [comment]
The bug I were experienced with is connecting with incorrect path auto-detection procedure. It adds endline symbol (or something like that)  to the end path field (so affected fields looks like memos). The workabout is -just remove endline symbols and turn off the autodetection feature at startup. Warning - If you exec the autodetection procedure (by pressing the toolbar button) the error appears again!

**Comment by vadixidav** [comment]
The auto detection is bugged then, so the issue should be reopened.

**Comment by vadixidav** [comment]
Is the autodetection not in this repo?
