### ISSUE TITLE
Add support for rustsym declaration lookup

### ISSUE THREAD

**Issue by zmanian** [vertexclique/tokamak#55]
https://github.com/trixnz/rustsym provides querying capabilities to find symbol declarations in rust code. We should integrate this into tokamak.

**Comment by zmanian** [comment]
I'm researching if https://github.com/dan-t/rusty-tags is a cleaner solution

**Comment by zmanian** [comment]
rusty-tags generates ctags files in either vi or emacs format. Rename to .tags and neither format seems to work.

Not sure why yet

**Comment by vertexclique** [comment]
Lookups are added with `0.4.0`.
* Go to definition.
* Hover over types
* Hover over for documentation.
* File outline.
