### ISSUE TITLE
Terminal does not refresh on ^L until next keystroke

### ISSUE THREAD

**Issue by mninja** [vertexclique/tokamak#59]
Steps to reproduce:
1. Open tokamak terminal (with `zsh` as shell)
2. Trigger some output (eg. `ls` or just hit enter)
3. Hit Ctrl-L

Expected: Screen is cleared
What happens: Screen freezes until the next input. After that, it clears (and you can see the new input).

Not a high priority since the clearing still works. Not sure if this is exclusive to `zsh`.

**Comment by mninja** [comment]
Some more information:

```
Atom    : 1.8.0
Electron: 0.36.12
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

`tokamak-terminal` is at `0.1.2`.

**Comment by vertexclique** [comment]
Latest version is v10.0.1 please update it. And for future issues please use https://github.com/vertexclique/tokamak-terminal/issues
