### ISSUE TITLE
Clicking on Terminal runs "Clean"

### ISSUE THREAD

**Issue by teekaay** [vertexclique/tokamak#6]
When I click on the "Terminal" button, the message `Tokamak: Cargo clean successful!` shows up, but not the terminal. Anyone else experienced this behavior?

Edit: I looked up the behavior of "Terminal" and it really runs clean as a callback. This is a little bit confusing in my opinion since there is a clean command available.

**Comment by vertexclique** [comment]
Yeah, I am trying to implement terminal future right now and I forgot it inside :grin: ASAP I will change it.

**Comment by teekaay** [comment]
Ah thanks for the information :) Looking forward to it!

**Comment by vertexclique** [comment]
@teekaay Terminal view implemented in v0.2.6. Now it opens a terminal view.
