### ISSUE TITLE
Rustup integration

### ISSUE THREAD

**Issue by mxmind** [vertexclique/tokamak#62]
Please add support of rustup.rs instead of multirust.

**Comment by zmanian** [comment]
I'm using rustup just fine with tokamak. We added support some time ago. What problem are you having?

**Comment by mxmind** [comment]
I'm assuming, it would be great to have some handy UI to work with rust toolchains using rustup commands. 
Having of some configuration to define release channels, checking new updates would be awesome.
Also, adding/removing targets, list of installed targets, switching between them will be really cool stuff.

**Comment by zmanian** [comment]
You can switch toolchains right now inside tokamak via rustup.

Other features could be added pretty easily

**Comment by PAStheLoD** [comment]
So, does tokamak require the multirust executable in a rustup environment? Because it currently doesn't auto-detect rustup.

**Comment by vertexclique** [comment]
Problems with rustup fixed. In upcoming release you can use rustup.

**Comment by vertexclique** [comment]
0.3.2 released. Update it please. 😊
