### ISSUE TITLE
Deprecated selector in `tokamak/styles/tokamak.less`

### ISSUE THREAD

**Issue by khinch** [vertexclique/tokamak#67]
In `tokamak/styles/tokamak.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .meta.attribute.rust` => `atom-text-editor.editor .syntax--meta.syntax--attribute.syntax--rust`

* `atom-text-editor::shadow .storage.modifier.lifetime.rust,
atom-text-editor::shadow .entity.name.lifetime.rust` => `atom-text-editor.editor .syntax--storage.syntax--modifier.syntax--lifetime.syntax--rust,
atom-text-editor.editor .syntax--entity.syntax--name.syntax--lifetime.syntax--rust`

* `atom-text-editor::shadow .keyword.unsafe.rust` => `atom-text-editor.editor .syntax--keyword.syntax--unsafe.syntax--rust`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by TheDoctorsLife** [comment]
I might just send a pr in for this a a day or do, I'd love to get rid of the annoying deprecation warning in atom.

**Comment by vertexclique** [comment]
Will be fixed in next release.

**Comment by vertexclique** [comment]
Fixed in 0.3.2 please update.
