### ISSUE TITLE
Tokamak enforces two space indents

### ISSUE THREAD

**Issue by mmstick** [vertexclique/tokamak#69]
With this extension enabled, Rust source code will be forced to use two space indents -- completely ignoring the global value. Happened with the latest update.

**Comment by mmstick** [comment]
Still observing this today. Will this ever be fixed?

**Comment by Lokidottir** [comment]
Seconded, 4 space indent is more readable for some including myself and I can't find how to switch back to it.

**Comment by mmstick** [comment]
Made this PR which fixes the issue: https://github.com/vertexclique/tokamak/pull/80

**Comment by sprowell** [comment]
A fix, of sorts, is to modify the `rust.cson` file that is part of the Tokamak package.  YMMV, but on the Mac I find this in:
`~/.atom/packages/tokamak/settings`

Just _remove_ the line about `'tabLength': 2` and you should be good.
