### ISSUE TITLE
Help Modal Doesn't Disappear

### ISSUE THREAD

**Issue by KodrAus** [vertexclique/tokamak#7]
Not sure if this is an Atom thing or not, but if I open up the 'About Tokamak' modal on OSX I have to quit Atom to make it disappear.

**Comment by mkpankov** [comment]
Same thing on Ubuntu 14.04

**Comment by ithamsteri** [comment]
And Windows 10 too.

**Comment by kevinpoitra** [comment]
Windows 7 as well.
