### ISSUE TITLE
OS X - default launch and env vars

### ISSUE THREAD

**Issue by nathansizemore** [vertexclique/tokamak#9]
~~~
OS X    10.11.4
Atom    1.6.0
rustc   1.7.0 (a5d1e7a59 2016-02-29)
cargo   0.8.0-nightly (28a0cbb 2016-01-17)

$ which rustc
/usr/local/bin/rustc

$ which cargo
/usr/local/bin/cargo
~~~

When launching Atom from the dock and installing this package, errors come up stating it cannot find those in `PATH`. Below that error message, it says if you have them, launch atom from the command line. What is the reasoning for this? Does it happen on Linux/Windows as well? If the issue is known, if someone could point me in the right direction, I wouldn't mind sending a PR to fix the issue across platforms.

**Comment by vertexclique** [comment]
It is well known bug because of launchctl forkage of process when launching from system apps like (Finder, Spotlight and Dock):
Here is the issue for it.

* atom/atom#6956

If you have a PR you are already welcomed.

**Comment by nathansizemore** [comment]
Word. Figured it had to be something internal to atom, but just wanted to make sure there was nothing I could within this repo to fix it, because I'm pretty pumped to have an "IDE" for Rust development.
