### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by MGlolenstine** [vertexclique/tokamak#92]
Is this project now dead?

I'm having some problems with the rendering of the UI, but I don't really know if this is ever going to be fixed.

**Comment by vertexclique** [comment]
This project actively seeking for maintainers. Currently it is passively maintained. I don't have time to fix possible problems.

**Comment by MGlolenstine** [comment]
I'd love to take it on myself, but I have no knowledge about creating Atom plugins.
